---
output:
  html_document:
    keep_md: yes
---
Chapter 04 Graphs
=================================================
This report creates the chapter graphs.

<!--  Set the working directory to the repository's base directory; this assumes the report is nested inside of only one directory.-->
```{r, echo=F, message=F}
library(knitr)
knitr::opts_knit$set(root.dir='../')  #Don't combine this call with any other chunk -especially one that uses file paths.
```

<!-- Set the report-wide options, and point to the external code file. -->
```{r set-options, echo=F}
report_render_start_time <- Sys.time()
opts_chunk$set(
  results = 'show',
  message = TRUE,
  comment = NA,
  tidy = FALSE,
  fig.height = 4,
  fig.width = 5.5,
  out.width = "550px", #This affects only the markdown, not the underlying png file.  The height will be scaled appropriately.
  fig.path = 'figure-png/',
  dev = "png",
  dpi = 400
  # fig.path = 'figure-pdf/',
  # dev = "pdf"#,
  # dev.args=list(pdf = list(colormodel = 'cmyk'))
)
echo_chunks <- FALSE
options(width=80) # Default width
read_chunk("./chapter-04/chapter-04.R")
```
<!-- Load the packages.  Suppress the output when loading packages. -->
```{r load-packages, echo=echo_chunks, message=FALSE}
```

<!-- Load any Global functions and variables declared in the R file.  Suppress the output. -->
```{r declare-globals, echo=echo_chunks, message=FALSE}
```

<!-- Declare any global functions specific to a Rmd output.  Suppress the output. -->
```{r, echo=echo_chunks, message=FALSE}
```

<!-- Load the datasets.   -->
```{r load-data, echo=echo_chunks, message=FALSE}
```

<!-- Tweak the datasets.   -->
```{r tweak-data, echo=echo_chunks, message=FALSE}
```

## Figure 4-1
```{r figure-04-01, echo=echo_chunks, fig.height=3}
```

## Figure 4-2
```{r figure-04-02, echo=echo_chunks, fig.height=3}
```

## Figure 4-3
```{r figure-04-03, echo=echo_chunks, fig.height=6}
```

## Figure 4-4
```{r figure-04-04, echo=echo_chunks, fig.height=3}
```

## Figure 4-5
```{r figure-04-05, echo=echo_chunks, fig.height=2, out.width="550px"}
```

## Figure 4-6
See Table A: Standard normal distribution.

## Figures 4-7
```{r figure-04-07, echo=echo_chunks, fig.height=3, fig.width=4.5, out.width="300px"}
```

## Figure 4-8
```{r figure-04-08, echo=echo_chunks, fig.width=3.5, fig.height=1.5, out.width="350px"}
```

## Figure 4-9
```{r figure-04-09, echo=echo_chunks, fig.height=3}
```

## Unused Graphics
```{r unused-variants-figure-04-04, echo=echo_chunks, fig.height=3}
```
```{r unused-variants-figure-04-08, echo=echo_chunks, fig.height=1.5}
```

<!-- The footer that's common to all reports. -->
```{r, child = "../common-code/footer.Rmd"}
```
