---
output:
  html_document:
    keep_md: yes
---
Chapter 12 Graphs
=================================================
This report creates the chapter graphs.

<!--  Set the working directory to the repository's base directory; this assumes the report is nested inside of only one directory.-->
```{r, echo=F, message=F}
library(knitr)
knitr::opts_knit$set(root.dir='../')  #Don't combine this call with any other chunk -especially one that uses file paths.
```

<!-- Set the report-wide options, and point to the external code file. -->
```{r set-options, echo=F}
report_render_start_time <- Sys.time()
opts_chunk$set(
  results = 'show',
  message = TRUE,
  comment = NA,
  tidy = FALSE,
  fig.width = 5.5,
  fig.height = 4,
  out.width = "550px", #This affects only the markdown, not the underlying png file.  The height will be scaled appropriately.
  fig.path = 'figure-png/',
  dev = "png",
  dpi = 400
  # fig.path = 'figure-pdf/',
  # dev = "pdf"
)
echoChunks <- FALSE
options(width=80) # Default width
read_chunk("./chapter-12/chapter-12.R")
```
<!-- Load the packages.  Suppress the output when loading packages. -->
```{r load-packages, echo=echoChunks, message=FALSE}
```

<!-- Load any Global functions and variables declared in the R file.  Suppress the output. -->
```{r declare-globals, echo=echoChunks, message=FALSE}
```

<!-- Declare any global functions specific to a Rmd output.  Suppress the output. -->
```{r, echo=echoChunks, message=FALSE}
```

<!-- Load the datasets. -->
```{r load-data, echo=echoChunks, message=FALSE}
```

<!-- Tweak the datasets. -->
```{r tweak-data, echo=echoChunks, message=FALSE}
```

## Figure 12-1
This figure will be typeset by the publisher.

## Figure 12-2

```{r figure-12-02, echo=echoChunks, fig.width=4, out.width="400px"}
```

## Figure 12-3

```{r figure-12-03, echo=echoChunks, fig.width=4, out.width="400px"}
```

## Figure 12-4

```{r figure-12-04, echo=echoChunks, fig.width=4, out.width="400px"}
```

## Figure 12-5
```{r figure-12-05, echo=echoChunks, fig.width=7.5, out.width="750px"}
```

## Figure 12-6
```{r figure-12-06, echo=echoChunks}
```

## Figure 12-7
Table of Critical *F* values.  Will be produced by publisher.

## Figure 12-8
```{r figure-12-08, echo=echoChunks}
```

## Figure 12-9
```{r figure-12-09, echo=echoChunks,  fig.height = 2.5, fig.width=4, out.width="400px"}
```

## Figure 12-10
```{r figure-12-10, echo=echoChunks}
```

## Figure 12-11
```{r figure-12-11, echo=echoChunks}
```

## Figure 12-12
```{r figure-12-12, echo=echoChunks}
```

## Figure 12-13
```{r figure-12-13, echo=echoChunks, fig.width=3.0, fig.height=2.0, out.width="300px"}
```

<!-- The footer that's common to all reports. -->
```{r, child = "../common-code/footer.Rmd"}
```
