---
output:
  html_document:
    keep_md: yes
    code_folding: hide
---
Tables
=================================================
This report creates the tables.

<!--  Set the working directory to the repository's base directory; this assumes the report is nested inside of only one directory.-->
```{r, echo=TRUE, message=F}
library(knitr)
knitr::opts_knit$set(root.dir='../')  #Don't combine this call with any other chunk -especially one that uses file paths.
```

<!-- Set the report-wide options, and point to the external code file. -->
```{r set-options, echo=TRUE}
report_render_start_time <- Sys.time()
opts_chunk$set(
  results = 'asis',
  message = TRUE,
  comment = NA,
  tidy = FALSE
)
echo_chunks <- TRUE
options(width=80) # Default width
read_chunk("./tables/tables.R")
```
<!-- Load the packages.  Suppress the output when loading packages. -->
```{r load-packages, echo=echo_chunks, message=FALSE}
```

<!-- Load any Global functions and variables declared in the R file.  Suppress the output. -->
```{r declare-globals, echo=echo_chunks, message=FALSE}
```

<!-- Declare any global functions specific to a Rmd output.  Suppress the output. -->
```{r, echo=echo_chunks, message=FALSE}
```

<!-- Load the datasets.   -->
```{r load-data, echo=echo_chunks, message=FALSE}
```

<!-- Tweak the datasets.   -->
```{r tweak-data, echo=echo_chunks, message=FALSE}
```

## Table A.1: Standard normal distribution
```{r z-area, echo=echo_chunks}
```

## Table B.1: Critical values for *t* distributions
```{r t-p-values, echo=echo_chunks}
```

## Table C.1: Critical values for *F* distributions
```{r f-p-values, echo=echo_chunks}
```

## Table D.1: Critical values for χ^2 distributions
```{r chi-square-p-values, echo=echo_chunks}
```

<!-- The footer that's common to all reports. -->
```{r, child = "../common-code/footer.Rmd"}
```
