Chapter 03 Graphs
=================================================
This report creates the chapter graphs.

<!--  Set the working directory to the repository's base directory; this assumes the report is nested inside of only one directory.-->
```{r, echo=TRUE, message=F} 
opts_knit$set(root.dir='../')  #Don't combine this call with any other chunk -espeically one that uses file paths.
```

<!-- Set the report-wide options, and point to the external code file. -->
```{r set_options, echo=TRUE}
require(knitr)
opts_chunk$set(
    results='show', 
    comment = NA, 
    tidy = FALSE,
    fig.width = 5.5, 
    fig.height = 4, 
    out.width = "600px", #This affects only the markdown, not the underlying png file.  The height will be scaled appropriately.
    fig.path = 'figure_rmd/',     
    dev = "png",
#     dev = "pdf",
    dpi = 400
)
options(width=120) #So the output is 50% wider than the default.
read_chunk("./Chapter03/Chapter03.R") 
```
<!-- Load the packages.  Suppress the output when loading packages. --> 
```{r LoadPackages, echo=TRUE, message=FALSE}
```

<!-- Load any Global functions and variables declared in the R file.  Suppress the output. --> 
```{r DeclareGlobals, echo=TRUE, results='show', message=FALSE}
```

<!-- Declare any global functions specific to a Rmd output.  Suppress the output. --> 
```{r, echo=TRUE, message=FALSE}
```

<!-- Load the datasets.   -->
```{r LoadDatasets, echo=TRUE, results='show', message=FALSE}
```

<!-- Tweak the datasets.   -->
```{r TweakDatasets, echo=TRUE, results='show', message=FALSE}
```

## Figure 3-1
```{r Figure03_01, echo=TRUE, results='show', message=TRUE, fig.height=2}
```

## Figure 3-2
```{r Figure03_02, echo=TRUE, results='show', message=TRUE}
```

## Figure 3-3
```{r Figure03_03, echo=TRUE, results='show', message=TRUE, fig.height=1.5, out.width=NULL, out.height="150px"}
```

## Figure 3-4
```{r Figure03_04, echo=TRUE, results='show', message=TRUE, fig.height=1.5, out.width=NULL, out.height="150px"}
```

## Figure 3-5
```{r Figure03_05, echo=TRUE, results='show', message=TRUE, fig.height=6.5, fig.width=3.5, out.width=NULL, out.height="800px"}
```

## Figure 3-6
```{r Figure03_06, echo=TRUE, results='show', message=TRUE}
```

## Figure 3-7
```{r Figure03_07, echo=TRUE, results='show', message=TRUE}
```

## Figure 3-8
```{r Figure03_08, echo=TRUE, results='show', message=TRUE}
```

## Figure 3-9
```{r Figure03_09, echo=TRUE, results='show', message=TRUE, fig.height=3.5, fig.width=2, out.width="200px"}
```

## Figure 3-10
```{r Figure03_10, echo=TRUE, results='show', message=TRUE, fig.height=3.5, fig.width=2, out.width="200px"}
```

## Figure 3-11
```{r Figure03_11, echo=TRUE, results='show', message=TRUE, fig.height=3.5, fig.width=2, out.width="200px"}
```

## Figure 3-12
```{r Figure03_12, echo=TRUE, results='show', message=TRUE, fig.height=3.5, fig.width=2, out.width="200px"}
```

## Figure 3-13
```{r Figure03_13, echo=TRUE, results='show', message=TRUE, fig.height=4, fig.width=4, out.width="600px"}
```

## Figure 3-14
```{r Figure03_14, echo=TRUE, results='show', message=TRUE, fig.height=4, fig.width=4, out.width="600px"}
```

## Figure 3-15
```{r Figure03_15, echo=TRUE, results='show', message=TRUE, fig.height=2, out.width=NULL, out.height="200px"}
```

## Figure 3-16
```{r Figure03_16, echo=TRUE, results='show', message=TRUE, fig.height=2, out.width=NULL, out.height="200px"}
```

## Figure 3-17
```{r Figure03_17, echo=TRUE, results='show', message=TRUE}
```

## Session Info
For the sake of documentation and reproducibility, the current report was build on a system using the following software.

```{r session_info, echo=FALSE}
cat("Report created by", Sys.info()["user"], "at", strftime(Sys.time(), "%F, %T %z"))
sessionInfo()
```
