---
output:
  html_document:
    keep_md: yes
    code_folding: hide
---
Chapter 14 Graphs
=================================================
This report creates the chapter graphs.

<!--  Set the working directory to the repository's base directory; this assumes the report is nested inside of only one directory.-->
```{r, echo=F, message=F}
knitr::opts_knit$set(root.dir='../')  #Don't combine this call with any other chunk -especially one that uses file paths.
```

<!-- Set the report-wide options, and point to the external code file. -->
```{r set-options, echo=F}
library(knitr)
report_render_start_time <- Sys.time()
opts_chunk$set(
  results = 'show',
  message = TRUE,
  comment = NA,
  tidy = FALSE,
  fig.height = 3.5,
  fig.width = 5.5,
  out.width = "400px", #This affects only the markdown, not the underlying png file.  The height will be scaled appropriately.

  fig.path = 'figure-png/',
  dev = "png",
  dpi = 400

#   fig.path = 'figure-pdf/',
#   dev = "pdf"#,
  # dev.args=list(pdf = list(colormodel = 'cmyk'))
)

echo_chunks <- TRUE
options(width=80) # Default width
read_chunk("./chapter-14/chapter-14.R")

```
<!-- Load the packages.  Suppress the output when loading packages. -->
```{r load-packages, echo=echo_chunks, message=FALSE}
```

<!-- Load any Global functions and variables declared in the R file.  Suppress the output. -->
```{r declare-globals, echo=echo_chunks, message=FALSE}
```

<!-- Declare any global functions specific to a Rmd output.  Suppress the output. -->
```{r, echo=echo_chunks, message=FALSE}
```

<!-- Load the datasets. -->
```{r load-data, echo=echo_chunks, message=FALSE}
```

<!-- Tweak the datasets. -->
```{r tweak-data, echo=echo_chunks, message=FALSE}
```

## Figure 14-2
```{r figure-14-02, echo=echo_chunks}
```

## Figure 14-3
[Steve Zissou](https://www.google.com/search?q=Steve+Zissou&espv=210&es_sm=93&tbm=isch&imgil=2g2Hl0Xn1uLPnM%253A%253Bhttps%253A%252F%252Fencrypted-tbn3.gstatic.com%252Fimages%253Fq%253Dtbn%253AANd9GcSs7l-wrHy3iVFP-U3qGDXiVc4UuWY2AIJo0WbGRJ9tnpUINC-I%253B1024%253B768%253BpIGucwvka7NrpM%253Bhttp%25253A%25252F%25252Ffuckyeahstevezissou.tumblr.com%25252Fpost%25252F11494722427%25252Fgood-moms-dress-their-children-as-steve-zissou&source=iu&usg=__NDOX2CzOV_P7y2LbbNYt2oaZ4aE%3D&sa=X&ei=Y6FEU7PfAo-S2AWn_YDICg&ved=0CLUBEP4dMA0#facrc=_&imgdii=_&imgrc=2g2Hl0Xn1uLPnM%253A%3BpIGucwvka7NrpM%3Bhttp%253A%252F%252Fwww.movies-wallpapers.net%252FMovies%252FThe%252520Life%252520Aquatic%252520With%252520Steve%252520Zissou%252FThe%252520Life%252520Aquatic%252520With%252520Steve%252520Zissou-10.jpg%3Bhttp%253A%252F%252Ffuckyeahstevezissou.tumblr.com%252Fpost%252F11494722427%252Fgood-moms-dress-their-children-as-steve-zissou%3B1024%3B768)

```{r figure-14-03, echo=echo_chunks}
```

## Figure 14-4
```{r figure-14-04, echo=echo_chunks}
```

## Figure 14-6
```{r figure-14-06, echo=echo_chunks}
```

## Figure 14-10
```{r figure-14-10, echo=echo_chunks}
```

<!-- The footer that's common to all reports. -->
```{r, child = "../common-code/footer.Rmd"}
```
